project:
  output-dir: _render/report

book:
  title: "Discrepancy in Riskesdas Methods"
  subtitle: "A comparison between SKI 2023 and Riskesdas 2018"
  author: "Aly Lamuri"
  chapters:
    - index.qmd
    - results/eda.qmd
    - results/model.qmd
    - results/scenario.qmd

in:
  report: true
